// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using SharpEmu.Core.Cpu.Native;
using Xunit;

namespace SharpEmu.Libs.Tests.Cpu;

// Regression for the Dreaming Sarah (PPSA02929) area-transition freeze.
//
// The VEH-entry recursive spinlock serializes managed exception-handler entry.
// Its acquire compare-exchange was emitted as `F0 4C 0F B1 11`, which decodes to
// `lock cmpxchg [rcx], r10` — REX.B was missing, so the r/m base was rcx (the
// handler's EXCEPTION_POINTERS argument) instead of r9 (the lock). The real lock
// word was never touched by the CAS, and whenever [rcx] read non-zero the CAS
// could never match the free lock value, so the faulting thread spun forever in
// the acquire loop and the game froze. The correct encoding is `F0 4D 0F B1 11`
// (`lock cmpxchg [r9], r10`). Every `lock cmpxchg` in the trampoline must target
// r9, never rcx.
public sealed class VehEntrySpinlockEncodingTests
{
    [Fact]
    public void VehEntrySpinlock_CompareExchange_TargetsLockRegisterNotRcx()
    {
        if (!OperatingSystem.IsWindows())
        {
            return; // The x86-64 VEH trampoline is only emitted on Windows.
        }

        // The trampoline builder only bakes fields as immediates and VirtualAllocs a
        // stub; it never executes it, so an uninitialised instance is sufficient to
        // inspect the generated bytes without standing up a full backend.
        var backend = (DirectExecutionBackend)RuntimeHelpers.GetUninitializedObject(
            typeof(DirectExecutionBackend));
        var method = typeof(DirectExecutionBackend).GetMethod(
            "CreateExceptionHandlerTrampoline",
            BindingFlags.NonPublic | BindingFlags.Instance);
        Assert.NotNull(method);

        var stub = (nint)method!.Invoke(backend, new object[] { (nint)0x1234 })!;
        Assert.NotEqual((nint)0, stub);

        var bytes = new byte[2048];
        Marshal.Copy(stub, bytes, 0, bytes.Length);

        var casSites = 0;
        for (var i = 0; i + 4 < bytes.Length; i++)
        {
            // lock (F0) REX (4x) cmpxchg (0F B1) ModRM
            if (bytes[i] != 0xF0 || bytes[i + 2] != 0x0F || bytes[i + 3] != 0xB1)
            {
                continue;
            }

            var rex = bytes[i + 1];
            if ((rex & 0xF0) != 0x40)
            {
                continue; // not a REX-prefixed form; ignore
            }

            var modrm = bytes[i + 4];
            // Must be REX.WRB (W|R|B) with ModRM 0x11 -> `lock cmpxchg [r9], r10`.
            // REX.B (0x01) is the bit that selects r9 over rcx as the r/m base.
            Assert.True(
                (rex & 0x01) != 0,
                $"VEH-entry CAS at offset {i} has REX=0x{rex:X2} (REX.B clear): the " +
                $"compare-exchange targets [rcx] instead of the lock [r9].");
            Assert.Equal(0x11, modrm);
            casSites++;
        }

        // Host-stack path and guest-stack path each emit one acquire CAS.
        Assert.True(casSites >= 2, $"expected >=2 VEH-entry CAS sites, found {casSites}");
    }
}
